# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

##########################################################################################
# Be sure to edit the values below
##########################################################################################

title: Federal Committee on Statistical Methodology (FCSM)
description: >- # this means to ignore newlines until "baseurl:"
  The Federal Committee on Statistical Methodology (FCSM) is an interagency committee dedicated to improving the quality of Federal statistics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.fcsm.gov" 
  # the base hostname & protocol for your site, e.g. https://example.com.
  # Required to support the jekyll-sitemap plugin below.
  # Uncomment the url line when ready to push to production. If using different branches for multiple
  # custom domains, edit this url parameter in the relevant branch to match the relevant custom domain.

#################################################################
#
# Digital Analytics Program (DAP) configuration
#
# USAID   - Agency for International Development
# USDA    - Department of Agriculture
# DOC     - Department of Commerce
# DOD     - Department of Defense
# ED      - Department of Education
# DOE     - Department of Energy
# HHS     - Department of Health and Human Services
# DHS     - Department of Homeland Security
# HUD     - Department of Housing and Urban Development
# DOJ     - Department of Justice
# DOL     - Department of Labor
# DOS     - Department of State
# DOI     - Department of the Interior
# TREAS   - Department of the Treasury
# DOT     - Department of Transportation
# VA      - Department of Veterans Affairs
# EPA     - Environmental Protection Agency
# EOP     - Executive Office of the President
# GSA     - General Services Administration
# NASA    - National Aeronautics and Space Administration
# NARA    - National Archives and Records Administration
# NSF     - National Science Foundation
# NRC     - Nuclear Regulatory Commission
# OPM     - Office of Personnel Management
# USPS    - Postal Service
# SBA     - Small Business Administration
# SSA     - Social Security Administration
#
#################################################################
dap:
   agency: GSA

  # Optional
  # subagency: your-subagency

# Configuration for Google Analytics
ga:
  # ua: your-ua

# Site Navigation
primary_navigation:
  - name: Home
    url: /
  - name: About FCSM
    url: /about/
  - name: Resources
    url: /resources/
  - name: Events and Proceedings
    url: /events/
  - name: Groups Overview
    url: /groups/

about_navigation:
  - name: About FCSM
    url: /about/
  - name: Charter
    collapsible: true
    int_url: /about/charter/
    children:
      - name: Background
        url: /about/charter/#background
      - name: Mission of the FCSM
        url: /about/charter/#mission
      - name: FCSM Activities
        url: /about/charter/#activities
      - name: Membership
        url: /about/charter/#membership
      - name: Subcommittees and Interest Groups
        url: /about/charter/#subcommittees
      - name: FCSM Products
        url: /about/charter/#products
      - name: Authority
        url: /about/charter/#authority
      - name: Signatures of ICSP Members
        url: /about/charter/#signatures
  - name: Members
    url: /about/members/

group_navigation:
  - name: Groups Overview
    url: /groups/
  - name: Interest Groups
    collapsible: true
    children:
      - name: Innovating Data Collection Interest Group
        url: /groups/idcig/
      - name: Confidentiality and Data Access Committee (CDAC)
        url: /groups/cdac/
      - name: Computational Statistics and the Production of Official Statistics (CSPOS) Interest Group
        url: /groups/cspos/
      - name: Geospatial Interest Group (GIG)
        url: /groups/gig/
      - name: Measuring Sexual Orientation and Gender Identity (SOGI) Research Group
        url: /groups/sogi/
  - name: Subcommittees
    collapsible: true
    children:
      - name: Federal Statistical System Research Subcommittee
        url: /groups/fssr-subcommittee/
      - name: Integrated Data Quality Subcommittee
        url: /groups/data-quality/
      - name: Subcommittee on Updating Statistical Methods for Safeguarding Protected Data
        url: /groups/data-safeguards/
      - name: Nonresponse Bias Working Group
        url: /groups/nonresponse-bias/

resource_navigation:
  - name: Resources Summary
    url: /resources/
  - name: Statistical Policy Working Papers
    url: /resources/statistical-policy-working-papers/
  - name: Data Protection toolkit
    url: /resources/safe-guard-data/
  - name: Data Quality
    url: /resources/data-quality-subcommittee/
  - name: Nonresponse Bias
    url: /resources/non-response-bias/
  - name: SOGI
    url: /resources/sogi/

events_navigation:
  - name: FCSM Research and Policy Conferences
    url: /events/fcsm-research-conferences/
  - name: Past FCSM Statistical Policy Seminars
    url: /events/fcsm-conference-seminar-programs-presentations/
  - name: Recordings of CDAC Meetings and Workshops
    url: /events/cdac-meetings/
  - name: GASP Presentations
    url: /events/gasp-presentations/
  - name: GIG Presentations
    url: /events/gig-presentations/

  # - name: FCSM Statistical Policy Seminars
  #   url: /events/fcsm-conference-seminar-programs-presentations/
  # - name: CDAC Meetings
  #   url: /events/cdac-meetings/
  # - name: GASP Presentations
  #   url: /events/gasp-presentations/
  # - name: GIG Presentations
  #   url: /events/gig-presentations/

# Search.gov configuration
#
# 1. Create an account with Search.gov https://search.usa.gov/signup
# 2. Add a new site.
# 3. Add your site/affiliate name here.
searchgov:

  # Only change this if you're using a CNAME. Learn more here: https://search.gov/manual/cname.html
  endpoint: https://search.usa.gov

  # Replace this with your search.gov account.
  affiliate: fcsm_gov

  # Replace this with your access key.
  access_key: BzW79eEDXU_NREd6lxgPPOkRapZsZdwcF43VjL_X33c=

  # This renders the results within the page instead of sending to user to search.gov.
  inline: true

  # This allows Search.gov to present relevant type-ahead search suggestions in your website's search box.
  # If you do not want to present search suggestions, set this value to false.
  suggestions: true

##########################################################################################
# The values below here are more advanced and should only be
# changed if you know what they do
##########################################################################################

collections:
  pages:
    output: true
    permalink: /:path/
  members:
    output: false

permalink: pretty

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true
  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false
  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: "posts"
  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 3
  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: "/page/:num/" # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.
  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ":title - page :num"
  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: "date"
  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true
  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: "posts"
  # Optional, the default tag to use, omit to disable
  tag: ""
  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts,
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: ""
  # Optional,omit or set both before and after to zero to disable.
  # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2
    after: 2
  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html
  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: "index.html"

exclude:
  - package.json
  - package-lock.json
  - README.md
  - CONTRIBUTING.md
  - LICENSE.md
  - degit.json
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - Dockerfile

assets:
  digest: false
  autoprefixer:
    browsers:
      - "> 2%"
      - "last 2 versions"
      - "IE 11"
      - "not dead"
  compression: true
  sources:
    - node_modules/uswds/dist
    - node_modules/uswds/dist/img
    - node_modules/uswds/dist/js
    - node_modules/uswds/dist/scss
    - node_modules/netlify-cms/dist
    - _assets/img
    - _assets/js
    - _assets/css
  defaults:
    js:  { integrity: false }
    css: { integrity: false }
    img: { integrity: false }
  features:
    integrity: false
